# Generated by Django 5.0 on 2023-12-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_result_exam_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='users',
        ),
        migrations.AddField(
            model_name='exam',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.user'),
        ),
    ]
