# Generated by Django 5.0 on 2023-12-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_exam_users_exam_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='users',
            new_name='user',
        ),
    ]
