# Generated by Django 5.0 on 2023-12-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_alter_result_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="virtual_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.virtualclass",
            ),
        ),
    ]
