# Generated by Django 5.0 on 2023-12-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_exam_score_delete_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="virtual_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="school.virtualclass",
            ),
        ),
    ]
